import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from './nav'
import { ConnectKitProvider } from '@/components/connectkit-provider'
import { ThemeProvider } from "@/components/theme-provider"
import { ContextProvider } from './context-provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: 'calc(100vh - 60px)' }}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConnectKitProvider>
            <ContextProvider>
              <Nav />
              {children}
            </ContextProvider>
          </ConnectKitProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
